#! /bin/bash
#--------------------------------------
# RunLawn
#--------------------------------------
NAME="Nicholas Ho"
echo "compliling Lawn.java"
javac Lawn.java >& Lawn-errs
echo "running Lawn.class"
java Lawn < Lawn-in > Lawn-out
echo "deleting the file Lawn.class"
rm Lawn.class
